//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Message", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AdjInvSuccess {
            get {
                return ResourceManager.GetString("AdjInvSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AdjReInv_Madjust {
            get {
                return ResourceManager.GetString("AdjReInv_Madjust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AdjReInv_MAdjustSuccess {
            get {
                return ResourceManager.GetString("AdjReInv_MAdjustSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AdjReInv_MAdjustUnsuccess {
            get {
                return ResourceManager.GetString("AdjReInv_MAdjustUnsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AdjReInv_MesAcceptInv {
            get {
                return ResourceManager.GetString("AdjReInv_MesAcceptInv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AdjReInv_MesAllLsts {
            get {
                return ResourceManager.GetString("AdjReInv_MesAllLsts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AdjReInv_MesLst {
            get {
                return ResourceManager.GetString("AdjReInv_MesLst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AdjReInv_MesNoRTemp {
            get {
                return ResourceManager.GetString("AdjReInv_MesNoRTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AdjReInv_MesPleaseWait {
            get {
                return ResourceManager.GetString("AdjReInv_MesPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AdjReInv_MesSignUnsuccess {
            get {
                return ResourceManager.GetString("AdjReInv_MesSignUnsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AdjReInv_MInvalidInv {
            get {
                return ResourceManager.GetString("AdjReInv_MInvalidInv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AdjReInv_MNoneCer {
            get {
                return ResourceManager.GetString("AdjReInv_MNoneCer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AdjReInv_MReFor {
            get {
                return ResourceManager.GetString("AdjReInv_MReFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AdjReInv_Mreplace {
            get {
                return ResourceManager.GetString("AdjReInv_Mreplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AdjReInv_MReplaceFor {
            get {
                return ResourceManager.GetString("AdjReInv_MReplaceFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AdjReInv_MReplaceSuccess {
            get {
                return ResourceManager.GetString("AdjReInv_MReplaceSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AdjReInv_MSendMail {
            get {
                return ResourceManager.GetString("AdjReInv_MSendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AdjReInv_MVerifyCer {
            get {
                return ResourceManager.GetString("AdjReInv_MVerifyCer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Cat_DMesSuccess {
            get {
                return ResourceManager.GetString("Cat_DMesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Cat_DMesUnsuccess {
            get {
                return ResourceManager.GetString("Cat_DMesUnsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Cat_IMesSuccess {
            get {
                return ResourceManager.GetString("Cat_IMesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Cat_IMesUnsuccess {
            get {
                return ResourceManager.GetString("Cat_IMesUnsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Cat_MesConfirmDel {
            get {
                return ResourceManager.GetString("Cat_MesConfirmDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Cat_UMesSuccess {
            get {
                return ResourceManager.GetString("Cat_UMesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Cat_UMesUnsuccess {
            get {
                return ResourceManager.GetString("Cat_UMesUnsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Cert_MesConfirmDel {
            get {
                return ResourceManager.GetString("Cert_MesConfirmDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Cer_DMesCantDel {
            get {
                return ResourceManager.GetString("Cer_DMesCantDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Cer_DMesSuccess {
            get {
                return ResourceManager.GetString("Cer_DMesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Com_IMesSuccess {
            get {
                return ResourceManager.GetString("Com_IMesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Com_MesErrFileSize {
            get {
                return ResourceManager.GetString("Com_MesErrFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Com_MessErrofiletail {
            get {
                return ResourceManager.GetString("Com_MessErrofiletail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Com_UMesInfSuccess {
            get {
                return ResourceManager.GetString("Com_UMesInfSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Conv_IMesSuccess {
            get {
                return ResourceManager.GetString("Conv_IMesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Conv_MesChooseInv {
            get {
                return ResourceManager.GetString("Conv_MesChooseInv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Conv_MesCSrc {
            get {
                return ResourceManager.GetString("Conv_MesCSrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Conv_MesCStore {
            get {
                return ResourceManager.GetString("Conv_MesCStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Conv_MesInvConverted {
            get {
                return ResourceManager.GetString("Conv_MesInvConverted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Conv_MesNotChooseInv {
            get {
                return ResourceManager.GetString("Conv_MesNotChooseInv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Conv_MUnsuccess {
            get {
                return ResourceManager.GetString("Conv_MUnsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Cus_DMesSuccess {
            get {
                return ResourceManager.GetString("Cus_DMesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Cus_IMesCantCreatUser {
            get {
                return ResourceManager.GetString("Cus_IMesCantCreatUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Cus_IMesDupCode {
            get {
                return ResourceManager.GetString("Cus_IMesDupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Cus_IMesDupUsername {
            get {
                return ResourceManager.GetString("Cus_IMesDupUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Cus_IMesSelectCreate {
            get {
                return ResourceManager.GetString("Cus_IMesSelectCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Cus_IMesSuccess {
            get {
                return ResourceManager.GetString("Cus_IMesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Cus_MesConfirmDel {
            get {
                return ResourceManager.GetString("Cus_MesConfirmDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Cus_UMesSuccess {
            get {
                return ResourceManager.GetString("Cus_UMesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Dec_DMesCantDel {
            get {
                return ResourceManager.GetString("Dec_DMesCantDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Dec_DMesSuccess {
            get {
                return ResourceManager.GetString("Dec_DMesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Dec_DMesUnsuccess {
            get {
                return ResourceManager.GetString("Dec_DMesUnsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Dec_IMesSuccess {
            get {
                return ResourceManager.GetString("Dec_IMesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Dec_IMesUnsuccess {
            get {
                return ResourceManager.GetString("Dec_IMesUnsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Dec_MesConfirmAccept {
            get {
                return ResourceManager.GetString("Dec_MesConfirmAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Dec_MesConfirmDel {
            get {
                return ResourceManager.GetString("Dec_MesConfirmDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Dec_MesConfirmSend {
            get {
                return ResourceManager.GetString("Dec_MesConfirmSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Dec_MesEffectiveDateBigToday {
            get {
                return ResourceManager.GetString("Dec_MesEffectiveDateBigToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Dec_MesErrDate {
            get {
                return ResourceManager.GetString("Dec_MesErrDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Dec_MesErrSelectDate {
            get {
                return ResourceManager.GetString("Dec_MesErrSelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Dec_MesToDateBigBeginDate {
            get {
                return ResourceManager.GetString("Dec_MesToDateBigBeginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Dec_UMesSuccess {
            get {
                return ResourceManager.GetString("Dec_UMesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Dec_UMesUnsuccess {
            get {
                return ResourceManager.GetString("Dec_UMesUnsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string InvAdj_MesConfirmDelProd {
            get {
                return ResourceManager.GetString("InvAdj_MesConfirmDelProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string InvAdj_MesErrDelProd {
            get {
                return ResourceManager.GetString("InvAdj_MesErrDelProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string InvAdj_MesErrInvNo {
            get {
                return ResourceManager.GetString("InvAdj_MesErrInvNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string InvAdj_MesWrongInvNo {
            get {
                return ResourceManager.GetString("InvAdj_MesWrongInvNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Key_IMesExits {
            get {
                return ResourceManager.GetString("Key_IMesExits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Key_IMesSuccess {
            get {
                return ResourceManager.GetString("Key_IMesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Key_MesNoKeyStoreInfo {
            get {
                return ResourceManager.GetString("Key_MesNoKeyStoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Key_MesReqConfig {
            get {
                return ResourceManager.GetString("Key_MesReqConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Key_MesSelectSuccess {
            get {
                return ResourceManager.GetString("Key_MesSelectSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Key_SMesNonexist {
            get {
                return ResourceManager.GetString("Key_SMesNonexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Key_SMesWrongPassToken {
            get {
                return ResourceManager.GetString("Key_SMesWrongPassToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Key_UMesSuccess {
            get {
                return ResourceManager.GetString("Key_UMesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MDaySend {
            get {
                return ResourceManager.GetString("MDaySend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MDaySend1 {
            get {
                return ResourceManager.GetString("MDaySend1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MInvCode {
            get {
                return ResourceManager.GetString("MInvCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MInvCreateDate {
            get {
                return ResourceManager.GetString("MInvCreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MInvCusName {
            get {
                return ResourceManager.GetString("MInvCusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MInvNo {
            get {
                return ResourceManager.GetString("MInvNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Minvoice {
            get {
                return ResourceManager.GetString("Minvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MInvPattern {
            get {
                return ResourceManager.GetString("MInvPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MInvPublishDate {
            get {
                return ResourceManager.GetString("MInvPublishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MInvSerial {
            get {
                return ResourceManager.GetString("MInvSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MInvStaffCreate {
            get {
                return ResourceManager.GetString("MInvStaffCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MInvStaffPublish {
            get {
                return ResourceManager.GetString("MInvStaffPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MInvStatus {
            get {
                return ResourceManager.GetString("MInvStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MInv_DMesNotAllow {
            get {
                return ResourceManager.GetString("MInv_DMesNotAllow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MInv_DMesSuccess {
            get {
                return ResourceManager.GetString("MInv_DMesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MInv_IMesLstProd {
            get {
                return ResourceManager.GetString("MInv_IMesLstProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MInv_IMesMissProd {
            get {
                return ResourceManager.GetString("MInv_IMesMissProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MInv_IMesSuccess {
            get {
                return ResourceManager.GetString("MInv_IMesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MInv_MesChooseInvToPublish {
            get {
                return ResourceManager.GetString("MInv_MesChooseInvToPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MInv_MesConfirmDel {
            get {
                return ResourceManager.GetString("MInv_MesConfirmDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MInv_MesConfirmPublish {
            get {
                return ResourceManager.GetString("MInv_MesConfirmPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MInv_MesError {
            get {
                return ResourceManager.GetString("MInv_MesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MInv_MesNotAllowDelLine {
            get {
                return ResourceManager.GetString("MInv_MesNotAllowDelLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MInv_MesNullInv {
            get {
                return ResourceManager.GetString("MInv_MesNullInv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MInv_MesReqInformation {
            get {
                return ResourceManager.GetString("MInv_MesReqInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MInv_MesWrongCode {
            get {
                return ResourceManager.GetString("MInv_MesWrongCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MInv_SMesNoPubAccess {
            get {
                return ResourceManager.GetString("MInv_SMesNoPubAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MInv_SMesRTemp {
            get {
                return ResourceManager.GetString("MInv_SMesRTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MInv_UMesCantEdit {
            get {
                return ResourceManager.GetString("MInv_UMesCantEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MInv_UMesRequestProd {
            get {
                return ResourceManager.GetString("MInv_UMesRequestProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MInv_UMesSuccess {
            get {
                return ResourceManager.GetString("MInv_UMesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mmonth {
            get {
                return ResourceManager.GetString("Mmonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MNonPubAccess {
            get {
                return ResourceManager.GetString("MNonPubAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MNullInvInLst {
            get {
                return ResourceManager.GetString("MNullInvInLst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MPleaseWait {
            get {
                return ResourceManager.GetString("MPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MRequestProd {
            get {
                return ResourceManager.GetString("MRequestProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MRequestRTemp {
            get {
                return ResourceManager.GetString("MRequestRTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mstt {
            get {
                return ResourceManager.GetString("Mstt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Myear {
            get {
                return ResourceManager.GetString("Myear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pay_MesConfirm {
            get {
                return ResourceManager.GetString("Pay_MesConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pay_MesSelectInv {
            get {
                return ResourceManager.GetString("Pay_MesSelectInv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pay_MesSuccess {
            get {
                return ResourceManager.GetString("Pay_MesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pay_MesUnsuccess {
            get {
                return ResourceManager.GetString("Pay_MesUnsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PInv_IMesSuccess {
            get {
                return ResourceManager.GetString("PInv_IMesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PInv_MInvNonExits {
            get {
                return ResourceManager.GetString("PInv_MInvNonExits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PInv_MInvNonExitsInTime {
            get {
                return ResourceManager.GetString("PInv_MInvNonExitsInTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PInv_MLaunch {
            get {
                return ResourceManager.GetString("PInv_MLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PInv_Msuccess {
            get {
                return ResourceManager.GetString("PInv_Msuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PLInv_ConfirmBatchPub {
            get {
                return ResourceManager.GetString("PLInv_ConfirmBatchPub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PLInv_MesErrChooseCert {
            get {
                return ResourceManager.GetString("PLInv_MesErrChooseCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PLInv_MesPubishSuccess {
            get {
                return ResourceManager.GetString("PLInv_MesPubishSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PLInv_Msuccess {
            get {
                return ResourceManager.GetString("PLInv_Msuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Prod_DMesSuccess {
            get {
                return ResourceManager.GetString("Prod_DMesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Prod_DMesUnsuccess {
            get {
                return ResourceManager.GetString("Prod_DMesUnsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Prod_IMesCodeExits {
            get {
                return ResourceManager.GetString("Prod_IMesCodeExits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Prod_IMesSuccess {
            get {
                return ResourceManager.GetString("Prod_IMesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Prod_IMesUnsuccess {
            get {
                return ResourceManager.GetString("Prod_IMesUnsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Prod_MesConfirmDel {
            get {
                return ResourceManager.GetString("Prod_MesConfirmDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Prod_UMesSuccess {
            get {
                return ResourceManager.GetString("Prod_UMesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Prod_UMesUnsuccess {
            get {
                return ResourceManager.GetString("Prod_UMesUnsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pub_DMesCantDel {
            get {
                return ResourceManager.GetString("Pub_DMesCantDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pub_DMesSuccess {
            get {
                return ResourceManager.GetString("Pub_DMesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pub_DMesUnsuccess {
            get {
                return ResourceManager.GetString("Pub_DMesUnsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pub_IMesSuccess {
            get {
                return ResourceManager.GetString("Pub_IMesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pub_IMesUnsuccess {
            get {
                return ResourceManager.GetString("Pub_IMesUnsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pub_MesConfirmAccept {
            get {
                return ResourceManager.GetString("Pub_MesConfirmAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pub_MesConfirmDel {
            get {
                return ResourceManager.GetString("Pub_MesConfirmDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pub_MesConfirmSend {
            get {
                return ResourceManager.GetString("Pub_MesConfirmSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pub_MesViewRegPattern {
            get {
                return ResourceManager.GetString("Pub_MesViewRegPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pub_MRegInvoice {
            get {
                return ResourceManager.GetString("Pub_MRegInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pub_UMesSuccess {
            get {
                return ResourceManager.GetString("Pub_UMesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pub_UMesUnsuccess {
            get {
                return ResourceManager.GetString("Pub_UMesUnsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ReCancel_MesCanceled {
            get {
                return ResourceManager.GetString("ReCancel_MesCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ReCancel_MesSuccess {
            get {
                return ResourceManager.GetString("ReCancel_MesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ReInvCP_Mtitle {
            get {
                return ResourceManager.GetString("ReInvCP_Mtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ReInvDetail_MesDelInv {
            get {
                return ResourceManager.GetString("ReInvDetail_MesDelInv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ReInvDetail_MesUseInv {
            get {
                return ResourceManager.GetString("ReInvDetail_MesUseInv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ReInvDetail_Mtitle {
            get {
                return ResourceManager.GetString("ReInvDetail_Mtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ReplaceInvSuccess {
            get {
                return ResourceManager.GetString("ReplaceInvSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ReUse_ReqTime {
            get {
                return ResourceManager.GetString("ReUse_ReqTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Role_DMesSuccess {
            get {
                return ResourceManager.GetString("Role_DMesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Role_DMesUnsuccess {
            get {
                return ResourceManager.GetString("Role_DMesUnsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Role_IMesSuccess {
            get {
                return ResourceManager.GetString("Role_IMesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Role_IMesUnsuccess {
            get {
                return ResourceManager.GetString("Role_IMesUnsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Role_MMissPer {
            get {
                return ResourceManager.GetString("Role_MMissPer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Role_UMesSuccess {
            get {
                return ResourceManager.GetString("Role_UMesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Role_UMesUnsuccess {
            get {
                return ResourceManager.GetString("Role_UMesUnsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RTemp_DMesSuccess {
            get {
                return ResourceManager.GetString("RTemp_DMesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RTemp_DMesUnsuccess {
            get {
                return ResourceManager.GetString("RTemp_DMesUnsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RTemp_IMesSuccess {
            get {
                return ResourceManager.GetString("RTemp_IMesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RTemp_MesConfirmDel {
            get {
                return ResourceManager.GetString("RTemp_MesConfirmDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RTemp_MesUsedPattern {
            get {
                return ResourceManager.GetString("RTemp_MesUsedPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RTemp_UMesSuccess {
            get {
                return ResourceManager.GetString("RTemp_UMesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Staff_DMesSuccess {
            get {
                return ResourceManager.GetString("Staff_DMesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Staff_DMesUnsuccess {
            get {
                return ResourceManager.GetString("Staff_DMesUnsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Staff_IMesCannotCreateUser {
            get {
                return ResourceManager.GetString("Staff_IMesCannotCreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Staff_IMesNotHaveUser {
            get {
                return ResourceManager.GetString("Staff_IMesNotHaveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Staff_IMesSuccess {
            get {
                return ResourceManager.GetString("Staff_IMesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Staff_IMesUserExits {
            get {
                return ResourceManager.GetString("Staff_IMesUserExits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Staff_MessDeleteStaff {
            get {
                return ResourceManager.GetString("Staff_MessDeleteStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Staff_UMesSuccess {
            get {
                return ResourceManager.GetString("Staff_UMesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Staff_UMesUnsuccess {
            get {
                return ResourceManager.GetString("Staff_UMesUnsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Tax_DMesSuccess {
            get {
                return ResourceManager.GetString("Tax_DMesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Tax_DMesUnsuccess {
            get {
                return ResourceManager.GetString("Tax_DMesUnsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Tax_IMesSuccess {
            get {
                return ResourceManager.GetString("Tax_IMesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Tax_IMesUnsuccess {
            get {
                return ResourceManager.GetString("Tax_IMesUnsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Tax_MesConfirmDel {
            get {
                return ResourceManager.GetString("Tax_MesConfirmDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Tax_UMesSuccess {
            get {
                return ResourceManager.GetString("Tax_UMesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Tax_UMesUnsuccess {
            get {
                return ResourceManager.GetString("Tax_UMesUnsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Temp_DMesSuccess {
            get {
                return ResourceManager.GetString("Temp_DMesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Temp_DMesUnsuccess {
            get {
                return ResourceManager.GetString("Temp_DMesUnsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Temp_IMesSuccess {
            get {
                return ResourceManager.GetString("Temp_IMesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Temp_MesConfirmDel {
            get {
                return ResourceManager.GetString("Temp_MesConfirmDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Temp_MesConfluentNameTemp {
            get {
                return ResourceManager.GetString("Temp_MesConfluentNameTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Temp_MesExistName {
            get {
                return ResourceManager.GetString("Temp_MesExistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Temp_MesWrongFormat {
            get {
                return ResourceManager.GetString("Temp_MesWrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Temp_UMesSuccess {
            get {
                return ResourceManager.GetString("Temp_UMesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string User_DMesSuccess {
            get {
                return ResourceManager.GetString("User_DMesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string User_IMesSuccess {
            get {
                return ResourceManager.GetString("User_IMesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string User_MesCantDel {
            get {
                return ResourceManager.GetString("User_MesCantDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string User_MesChangePasswordSuccess {
            get {
                return ResourceManager.GetString("User_MesChangePasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string User_MesConfirmDel {
            get {
                return ResourceManager.GetString("User_MesConfirmDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string User_MesConfirmPass {
            get {
                return ResourceManager.GetString("User_MesConfirmPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string User_MesErrConfirmPas {
            get {
                return ResourceManager.GetString("User_MesErrConfirmPas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string User_MesErrConfirmPass {
            get {
                return ResourceManager.GetString("User_MesErrConfirmPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string User_MesInvalidUserOrPass {
            get {
                return ResourceManager.GetString("User_MesInvalidUserOrPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string User_MesNewPassLikeOldPass {
            get {
                return ResourceManager.GetString("User_MesNewPassLikeOldPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string User_MesNotSameOldPass {
            get {
                return ResourceManager.GetString("User_MesNotSameOldPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string User_MesReqConfirmNewPass {
            get {
                return ResourceManager.GetString("User_MesReqConfirmNewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string User_MesReqMinLengthPass {
            get {
                return ResourceManager.GetString("User_MesReqMinLengthPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string User_MesReqNewPass {
            get {
                return ResourceManager.GetString("User_MesReqNewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string User_MesReqOldPass {
            get {
                return ResourceManager.GetString("User_MesReqOldPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string User_MesRetypePass {
            get {
                return ResourceManager.GetString("User_MesRetypePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string User_MesWrongAccOrPass {
            get {
                return ResourceManager.GetString("User_MesWrongAccOrPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string User_MesWrongPass {
            get {
                return ResourceManager.GetString("User_MesWrongPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string User_UMesCantEdit {
            get {
                return ResourceManager.GetString("User_UMesCantEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string User_UMesExits {
            get {
                return ResourceManager.GetString("User_UMesExits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string User_UMesSuccess {
            get {
                return ResourceManager.GetString("User_UMesSuccess", resourceCulture);
            }
        }
    }
}
